/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

public class App {

    public static void main(String[] args) throws InterruptedException {
        Game game = new Game();
        game.start();
    }
}
